version: "3.3"

services:
  mysql:
    image: mysql
    container_name: mysql-rentx
    restart: unless-stopped
    ports:
      - 3306:3306
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_DATABASE=rentx
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

  redis:
    image: 'bitnami/redis:latest'
    container_name: redis-pi
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=abc123

  app:
    build: .
    container_name: rentx
    restart: unless-stopped
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis



volumes:
  db-config:
    driver: local
  db-data:
    driver: local
